import {defaultProfile,cleanRecord,cleanProfile,parseJournal,publicJournal,mergeRecords,courses,mapLink,pageUrl} from './core.js';
import {readLocal,changeLocal} from './storage.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const params=new URLSearchParams(location.search), owner=params.get('edit')==='1', preview=params.get('preview')==='1';
document.body.dataset.mode=owner?'owner':'reader';
const paths={plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',search:'m21 21-5-5M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0',camera:'M4 6h3l2-3h6l2 3h3v14H3V6ZM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',bookmark:'M6 3h12v18l-6-4-6 4Z',route:'M5 5h11a4 4 0 0 1 0 8H8a4 4 0 0 0 0 8h11M3 3h4v4H3Zm14 16h4v4h-4Z',share:'M12 16V3m-4 4 4-4 4 4M5 11H3v10h18V11h-2',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2'};
const icon=name=>'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name]||paths.pin)+'"/></svg>';
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let journal={version:1,profile:defaultProfile,records:[]}, demo=false, view=params.has('trip')?'courses':'all', region='all', search='',category='all',sort='recent', tripFilter=params.get('trip')||'';
const expandedCourses=new Set(tripFilter?[tripFilter]:[]);
let editingId=null, photo='', rating=0, dirty=false, busy=false, selectedId=null, undoRecord=null, imported=null, connection=null, snapshot=null, localReady=false, loadFailed=false, toastTimer;
const channel='BroadcastChannel' in window?new BroadcastChannel('hanip-journal-events'):null;
function errorIn(id,message){$(id).textContent=message;$(id).hidden=!message;}
function toast(message,undo=false){clearTimeout(toastTimer);$('#toast-message').textContent=message;$('#undo-button').hidden=!undo;$('#toast').hidden=false;if(!undo)toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function show(id){$(id).showModal();}
const dateLabel=d=>d?d.replaceAll('-','.'):'';const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const demoRecords=[
{id:'demo-1',name:'바다 앞 작은 식당',area:'강릉',category:'양식',trip:'강릉에서 보낸 느린 하루',day:1,order:1,menu:'토마토 부라타',note:'햇살 좋은 창가에서 천천히 먹었던 점심. 이런 식으로 나만의 감상을 남겨보세요.',rating:5,favorite:true,demoPhoto:true},
{id:'demo-2',name:'해변 따라 걷기',area:'강릉',category:'여행지',trip:'강릉에서 보낸 느린 하루',day:1,order:2,note:'점심을 먹고 바닷가를 산책했어요. 맛집 사이에 여행지도 함께 넣을 수 있어요.',rating:5},
{id:'demo-3',name:'골목 안 작은 카페',area:'강릉',category:'카페·디저트',trip:'강릉에서 보낸 느린 하루',day:1,order:3,menu:'따뜻한 라테',note:'하루의 마지막은 커피 한 잔. 순서대로 모으면 하나의 여행 코스가 완성돼요.',rating:4}
].map((r,i)=>({...cleanRecord({...r,status:'visited',published:true,visitDate:'2026-09-20',createdAt:'2026-09-2'+i+'T10:00:00Z',updatedAt:'2026-09-23T10:00:00Z'}),demoPhoto:r.demoPhoto}));
function currentRecords(){return demo?demoRecords:journal.records;}
function filtered(){return currentRecords().filter(r=>(region==='all'||r.area===region)&&(category==='all'||r.category===category)&&(view!=='favorite'||r.favorite)&&(!tripFilter||r.trip===tripFilter)&&[r.name,r.area,r.menu,r.note,r.trip,r.category].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='rating'?b.rating-a.rating:sort==='name'?a.name.localeCompare(b.name,'ko'):sort==='visit'?b.visitDate.localeCompare(a.visitDate):b.createdAt.localeCompare(a.createdAt));}
function photoMarkup(r,cls=''){return r.photo||r.demoPhoto?'<img class="'+cls+'" src="'+(r.demoPhoto?'./assets/food-editorial.png':esc(r.photo))+'" alt="'+esc(r.name)+' 사진" loading="lazy">':'<span class="card-placeholder" aria-hidden="true">'+(r.category==='여행지'?'journey.':r.category==='숙소'?'stay.':r.category==='카페·디저트'?'coffee.':'taste.')+'</span>';}
function card(r){return '<article class="card"><button class="card-open" data-detail="'+esc(r.id)+'" aria-label="'+esc(r.name)+' 기록 보기"><div class="card-photo">'+photoMarkup(r)+(r.visitDate?'<span class="card-date">'+dateLabel(r.visitDate)+'</span>':'')+'</div><div class="card-body"><div class="card-meta"><span class="category-label">'+esc(r.category)+'</span><span>'+esc(r.area||'지역 미등록')+'</span>'+(owner&&!demo?'<span class="visibility-label">'+(r.published?'공개 대상':'나만 보기')+'</span>':'')+'</div><h2>'+esc(r.name)+'</h2><div class="card-rating" aria-label="'+(r.rating?'5점 중 '+r.rating+'점':'별점 없음')+'">'+(r.status==='wishlist'?'가보고 싶은 곳':r.rating?'★'.repeat(r.rating)+'☆'.repeat(5-r.rating):'')+'</div><p class="card-note">'+esc(r.note||r.menu||'아직 남긴 메모가 없어요.')+'</p>'+(r.trip?'<div class="card-trip">'+icon('route')+esc(r.trip)+' · DAY '+r.day+'</div>':'')+'</div></button>'+(owner&&!demo?'<button class="favorite-button '+(r.favorite?'selected':'')+'" data-favorite="'+esc(r.id)+'" aria-label="'+esc(r.name)+' 다시 가고 싶은 곳 '+(r.favorite?'해제':'지정')+'" aria-pressed="'+r.favorite+'">'+icon('heart')+'</button>':'')+'</article>';}
function courseHtml(course,allRecords,index){const expanded=expandedCourses.has(course.name),contentId='course-content-'+index;const days=[...new Set(course.stops.map(r=>r.day))];return '<section class="course'+(expanded?' is-open':'')+'"><div class="course-header"><h2 class="course-heading"><button class="course-toggle" data-toggle-course="'+esc(course.name)+'" aria-expanded="'+expanded+'" aria-controls="'+contentId+'"><span class="course-summary"><span class="course-name">'+esc(course.name)+'</span><span class="course-meta">'+[...new Set(course.stops.map(r=>r.area).filter(Boolean))].map(esc).join(' · ')+' <span> / '+course.stops.length+'곳</span></span></span><span class="course-disclosure"><span class="course-toggle-label">'+(expanded?'접기':'펼치기')+'</span><svg class="icon course-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></span></button></h2><button class="secondary" data-share-trip="'+esc(course.name)+'" aria-label="'+esc(course.name)+' 코스 공유">'+icon('share')+'코스 공유</button></div><div class="course-content" id="'+contentId+'"'+(expanded?'':' hidden')+'>'+(allRecords.filter(r=>r.trip===course.name).length!==course.stops.length?'<p class="helper">필터에 맞는 장소만 표시 중이에요. 필터를 해제하면 전체 코스를 볼 수 있어요.</p>':'')+days.map(day=>'<div class="course-day"><span class="day-label">DAY '+day+'</span><ol>'+course.stops.filter(r=>r.day===day).map(r=>'<li><span class="stop-number">'+r.order+'</span><div class="stop-info"><span class="card-meta">'+esc(r.category)+' · '+esc(r.area)+'</span><button class="stop-title" data-detail="'+esc(r.id)+'">'+esc(r.name)+'</button><p>'+esc(r.note||r.menu)+'</p><a href="'+esc(mapLink(r))+'" target="_blank" rel="noopener noreferrer">'+icon('pin')+'지도에서 보기</a></div>'+(r.photo||r.demoPhoto?'<button class="stop-image" data-detail="'+esc(r.id)+'" aria-label="'+esc(r.name)+' 기록 보기">'+photoMarkup(r)+'</button>':'')+'</li>').join('')+'</ol></div>').join('')+'</div></section>';}
function setNotice(message,isError=false){$('#notice').hidden=false;$('#notice').classList.toggle('error',isError);$('#notice').textContent=message;}
function render(){
 const records=currentRecords(),list=filtered();$('#total-count').textContent=String(records.length).padStart(2,'0');$('#all-count').textContent=records.length;
 $('#journal-title').textContent=journal.profile.title;$('#journal-subtitle').textContent=journal.profile.subtitle;document.title=journal.profile.title+' · 한 입의 기억';
 $$('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});
 const areas=[...new Set(records.map(r=>r.area).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));
 $('#regions').innerHTML=areas.length?'<button class="region-chip '+(region==='all'?'active':'')+'" data-region="all" aria-pressed="'+(region==='all')+'">모든 지역 <span>'+records.length+'</span></button>'+areas.map(a=>'<button class="region-chip '+(region===a?'active':'')+'" data-region="'+esc(a)+'" aria-pressed="'+(region===a)+'">'+esc(a)+' <span>'+records.filter(r=>r.area===a).length+'</span></button>').join(''):'';
 const grouped=courses(list);$('#records').classList.toggle('courses',view==='courses');$('#records').innerHTML=view==='courses'?grouped.map((c,index)=>courseHtml(c,records,index)).join(''):list.map(card).join('');
 $('#result-count').textContent=records.length?(view==='courses'?grouped.length+'개의 여행 코스':list.length+'곳의 기록')+(tripFilter?' · '+tripFilter:''):'아직 기록이 없어요';
 $('#empty').hidden=records.length>0||loadFailed;$('#no-results').hidden=records.length===0||((view==='courses'?grouped.length:list.length)>0);
 $('#no-results h2').textContent=view==='courses'&&!grouped.length?'아직 묶인 여행 코스가 없어요':'찾는 기록이 없어요';$('#no-results p').textContent=view==='courses'?'기록에 같은 여행 이름을 적으면 방문 순서대로 모여요.':'다른 검색어나 지역, 종류로 찾아보세요.';
 $('#demo-button').textContent=demo?'예시 닫기':'예시 구경하기';$('#preview-button').disabled=demo;$('#publish-button').disabled=demo||!localReady;$('#backup-button').disabled=demo||!localReady;
 $('#trip-list').innerHTML=[...new Set(journal.records.map(r=>r.trip).filter(Boolean))].map(t=>'<option value="'+esc(t)+'"></option>').join('');
 if(demo)setNotice('예시 화면이에요. 장소와 후기는 사용법을 보여주기 위한 가상 기록이며 저장·공개되지 않아요.');
 else if(loadFailed){}else if(preview)setNotice('공개될 내용의 미리보기예요. 이 주소는 다른 사람에게 공유할 수 없어요.');
 else if(owner)setNotice('내 기록 관리 · 기록은 이 기기에 저장돼요. 선택한 기록만 ‘공개하기’로 공유하세요.');
 else $('#notice').hidden=true;
}
function clearFilters(){search='';category='all';region='all';tripFilter='';$('#search').value='';$('#category-filter').value='all';render();}
function renderStars(){$('#rating-input').innerHTML=[1,2,3,4,5].map(n=>'<label class="'+(n<=rating?'filled':'')+'"><input type="radio" name="rating" value="'+n+'" aria-label="'+n+'점" '+(rating===n?'checked':'')+'><span aria-hidden="true">★</span></label>').join('');}
function renderPhoto(){$('#photo-preview').hidden=!photo;$('#photo-hint').hidden=!!photo;$('#remove-photo').hidden=!photo;if(photo)$('#photo-preview').src=photo;else $('#photo-preview').removeAttribute('src');}
function editorValue(){const f=new FormData($('#entry-form'));return {name:f.get('name'),area:f.get('area'),category:f.get('category'),status:f.get('status'),visitDate:f.get('status')==='wishlist'?'':f.get('visitDate'),rating:f.get('status')==='wishlist'?0:rating,menu:f.get('menu'),note:f.get('note'),mapUrl:f.get('mapUrl'),trip:f.get('trip'),day:f.get('day'),order:f.get('order'),favorite:f.has('favorite'),published:f.has('published'),photo};}
function openEditor(record){if(!owner){location.href='?edit=1';return;}if(!localReady){toast('기기 저장소를 사용할 수 없어요. 브라우저 저장 권한을 확인해 주세요.');return;}if(demo){demo=false;render();}editingId=record?.id||null;$('#entry-form').reset();photo=record?.photo||'';rating=record?.rating||0;errorIn('#editor-error','');$('#draft-notice').hidden=true;
 let values=record;if(!record){try{values=JSON.parse(sessionStorage.getItem('hanip-draft')||'null');if(values)$('#draft-notice').hidden=false;}catch{}}
 if(values){for(const [key,value]of Object.entries(values)){const field=$('[name="'+key+'"]');if(!field)continue;if(key==='status')$('[name="status"][value="'+(value==='wishlist'?'wishlist':'visited')+'"]').checked=true;else if(field.type==='checkbox')field.checked=value===true;else if(field.tagName!=='INPUT'||field.type!=='radio')field.value=String(value??'');}rating=values.rating||0;}else $('#visit-date').value=today();
 $('#editor-title').textContent=record?'기억 다듬기':'여행의 한 장면 남기기';renderPhoto();renderStars();$('#visit-fields').hidden=$('[name="status"]:checked').value==='wishlist';dirty=false;show('#editor');
}
async function updateLocal(fn){if(!owner||!localReady)throw Error('내 기록 관리 화면에서 저장할 수 있어요.');journal=await changeLocal(fn);channel?.postMessage('changed');render();return journal;}
async function saveEntry(event){event.preventDefault();if(busy)return;errorIn('#editor-error','');const values=editorValue();if(!values.name.trim()){errorIn('#editor-error','장소 이름을 입력해 주세요.');return;}if(values.mapUrl&&!/^https?:\/\//i.test(values.mapUrl)){errorIn('#editor-error','지도 링크는 https:// 또는 http://로 시작해야 해요.');return;}
 busy=true;$('#save-button').disabled=true;try{const existing=journal.records.find(r=>r.id===editingId);const record=cleanRecord({...values,id:editingId||crypto.randomUUID(),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});await updateLocal(j=>({...j,records:[...j.records.filter(r=>r.id!==record.id),record]}));dirty=false;try{sessionStorage.removeItem('hanip-draft');}catch{}$('#editor').close();toast('이 기기에 기록을 저장했어요.');}catch(e){errorIn('#editor-error',e.message);}finally{busy=false;$('#save-button').disabled=false;}
}
async function compressPhoto(file){if(file.size>25*1024*1024)throw Error('25MB 이하의 사진을 선택해 주세요.');if(!/^image\//.test(file.type))throw Error('사진 파일을 선택해 주세요.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;try{await img.decode();}catch{throw Error('이 사진을 읽을 수 없어요. JPG, PNG, WebP 사진을 선택해 주세요.');}const canvas=document.createElement('canvas');const scale=Math.min(1,1000/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);let quality=.8,data;do{data=canvas.toDataURL('image/jpeg',quality);quality-=.12;}while(data.length>450000&&quality>.2);if(data.length>600000)throw Error('사진이 너무 커요. 조금 작은 사진을 선택해 주세요.');return data;}finally{URL.revokeObjectURL(url);}}
function openDetail(id){const r=currentRecords().find(r=>r.id===id);if(!r)return;selectedId=id;$('#detail-content').innerHTML='<div class="detail-header">'+(r.photo||r.demoPhoto?photoMarkup(r,'detail-photo'):'')+'<button class="icon-button" data-close="detail" aria-label="기록 상세 닫기">'+icon('close')+'</button></div><div class="dialog-body"><div class="card-meta"><span class="category-label">'+esc(r.category)+'</span>'+esc(r.area)+(demo?'<span>예시</span>':'')+'</div><h2 id="detail-title" class="detail-title">'+esc(r.name)+'</h2><div class="card-rating" aria-label="5점 중 '+r.rating+'점">'+(r.rating?'★'.repeat(r.rating)+'☆'.repeat(5-r.rating):r.status==='wishlist'?'가보고 싶은 곳':'')+'</div>'+(r.visitDate?'<div class="detail-line">'+dateLabel(r.visitDate)+' 방문</div>':'')+(r.trip?'<div class="detail-line">'+icon('route')+esc(r.trip)+' · DAY '+r.day+' · '+r.order+'번째</div>':'')+(r.menu?'<div class="detail-menu"><small>기억하고 싶은 메뉴</small>'+esc(r.menu)+'</div>':'')+'<p class="detail-note">'+esc(r.note||'아직 남긴 메모가 없어요.')+'</p><a class="map-link" href="'+esc(mapLink(r))+'" target="_blank" rel="noopener noreferrer">'+icon('pin')+'지도에서 보기</a>'+(owner&&!demo?'<div class="detail-actions"><button class="text-button" id="delete-entry">기록 삭제</button><button class="primary" id="edit-entry">기록 수정하기</button></div>':'')+'</div>';show('#detail');}
function openPublish(){snapshot=publicJournal(journal);$('#publish-summary').textContent='장소 '+snapshot.records.length+'곳 · 여행 코스 '+courses(snapshot.records).length+'개 공개';connection=null;$('#upload-button').hidden=true;$('#remote-summary').textContent='';$('#publish-result').textContent='';errorIn('#connect-error','');show('#publish');}
function downloadJSON(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function guessRepository(){if(location.hostname.endsWith('.github.io')){const account=location.hostname.split('.')[0],repo=location.pathname.split('/').filter(Boolean)[0];return account+'/'+(repo&&!repo.includes('.')?decodeURIComponent(repo):account+'.github.io');}return '';}
async function githubRequest(path,{method='GET',body,allow404=false}={}){const token=$('#github-token').value.trim();const response=await fetch('https://api.github.com'+path,{method,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(25000)});if(allow404&&response.status===404)return null;if(!response.ok){const msgs={401:'연결 키가 올바르지 않거나 만료됐어요.',403:'접근 권한이나 GitHub 요청 한도를 확인해 주세요.',404:'저장소를 찾을 수 없어요. 이름과 연결 키의 접근 권한을 확인해 주세요.',409:'다른 곳에서 공개 기록이 변경됐어요. 공개 페이지를 확인하고 저장소를 다시 연결해 주세요.',422:'기본 브랜치와 브랜치 보호 규칙을 확인해 주세요.'};throw Error(msgs[response.status]||'GitHub에서 요청을 처리하지 못했어요 ('+response.status+'). 잠시 뒤 다시 시도해 주세요.');}return response.json();}
async function connect(event){event.preventDefault();errorIn('#connect-error','');const repo=$('#repository').value.trim();if(!/^[A-Za-z0-9-]+\/[A-Za-z0-9_.-]+$/.test(repo)){errorIn('#connect-error','계정이름/저장소이름 형식으로 입력해 주세요.');return;}$('#connect-button').disabled=true;connection=null;$('#upload-button').hidden=true;try{const info=await githubRequest('/repos/'+repo);if(info.private)throw Error('사이트 파일이 있는 공개 저장소를 선택해 주세요.');const remote=await githubRequest('/repos/'+repo+'/contents/public.json?ref='+encodeURIComponent(info.default_branch),{allow404:true});connection={repo,branch:info.default_branch,sha:remote?.sha};$('#remote-summary').textContent=repo+'의 public.json을 현재 선택한 '+snapshot.records.length+'개 공개 기록으로 '+(remote?'교체':'생성')+'해요. 기존 공개 목록 전체가 바뀝니다.';$('#upload-button').hidden=false;try{localStorage.setItem('hanip-site-repository',repo);}catch{}}catch(e){errorIn('#connect-error',e.name==='TimeoutError'?'연결 시간이 오래 걸려요. 다시 시도해 주세요.':e.message);}finally{$('#connect-button').disabled=false;}}
async function publish(){if(!connection||busy)return;busy=true;$('#upload-button').disabled=true;$('#connect-button').disabled=true;errorIn('#connect-error','');try{const bytes=new TextEncoder().encode(JSON.stringify(snapshot));if(bytes.length>8*1024*1024)throw Error('공개 기록이 8MB를 넘어요. 사진 수를 줄이거나 공개용 파일을 직접 업로드해 주세요.');let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));const result=await githubRequest('/repos/'+connection.repo+'/contents/public.json',{method:'PUT',body:{message:'Update public travel journal',branch:connection.branch,content:btoa(binary),...(connection.sha?{sha:connection.sha}:{})}});connection.sha=result.content.sha;const link=pageUrl(connection.repo);$('#publish-result').innerHTML='공개 파일을 GitHub에 저장했어요. 사이트 반영까지 몇 분 걸릴 수 있어요. <a href="'+esc(link)+'" target="_blank" rel="noopener noreferrer">공개 페이지 열기</a>';toast('공개용 파일을 저장했어요. GitHub Pages 반영을 기다려 주세요.');}catch(e){errorIn('#connect-error',e.message);}finally{busy=false;$('#upload-button').disabled=false;$('#connect-button').disabled=false;}}
async function shareTrip(trip){if(demo){toast('예시 코스는 공유할 수 없어요. 나만의 기록을 먼저 남겨 주세요.');return;}if(owner||preview){toast('게시한 뒤 공개 페이지에서 코스를 공유해 주세요.');return;}const u=new URL(location.href);u.search='';if(trip)u.searchParams.set('trip',trip);u.hash='';if(navigator.share){try{await navigator.share({title:trip||journal.profile.title,url:u.href});return;}catch(e){if(e.name==='AbortError')return;}}try{await navigator.clipboard.writeText(u.href);toast('공유 링크를 복사했어요.');}catch{$('#share-link-input').value=u.href;show('#share-link');$('#share-link-input').select();}}
document.addEventListener('click',async event=>{
 const b=event.target.closest('button');if(!b)return;
 if(b.dataset.close){$('#'+b.dataset.close).close();return;}
 if(b.dataset.action==='new'){openEditor();return;}
 if(b.dataset.view){view=b.dataset.view;tripFilter='';render();return;}
 if(b.dataset.region){region=b.dataset.region;render();return;}
 if(b.dataset.detail){openDetail(b.dataset.detail);return;}
 if(b.dataset.toggleCourse){const expanded=b.getAttribute('aria-expanded')!=='true';if(expanded)expandedCourses.add(b.dataset.toggleCourse);else expandedCourses.delete(b.dataset.toggleCourse);b.setAttribute('aria-expanded',String(expanded));b.querySelector('.course-toggle-label').textContent=expanded?'접기':'펼치기';$('#'+b.getAttribute('aria-controls')).hidden=!expanded;b.closest('.course').classList.toggle('is-open',expanded);return;}
 if(b.dataset.shareTrip){await shareTrip(b.dataset.shareTrip);return;}
 if(b.dataset.favorite){try{await updateLocal(j=>({...j,records:j.records.map(r=>r.id===b.dataset.favorite?{...r,favorite:!r.favorite,updatedAt:new Date().toISOString()}:r)}));}catch(e){toast(e.message);}return;}
 if(b.id==='edit-entry'){const record=journal.records.find(r=>r.id===selectedId);$('#detail').close();openEditor(record);}
 if(b.id==='delete-entry')show('#confirm');
});
$('#entry-form').addEventListener('submit',saveEntry);
$('#entry-form').addEventListener('input',()=>{dirty=true;if(!editingId){try{sessionStorage.setItem('hanip-draft',JSON.stringify({...editorValue(),photo:''}));}catch{}}});
$('#entry-form').addEventListener('change',event=>{if(event.target.name==='rating'){rating=Number(event.target.value);renderStars();}if(event.target.name==='status')$('#visit-fields').hidden=event.target.value==='wishlist';});
$('#photo-input').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;$('#save-button').disabled=true;errorIn('#editor-error','');try{photo=await compressPhoto(file);dirty=true;renderPhoto();}catch(e){errorIn('#editor-error',e.message);}finally{$('#save-button').disabled=false;event.target.value='';}});
$('#remove-photo').addEventListener('click',()=>{photo='';dirty=true;renderPhoto();});
$('#search').addEventListener('input',e=>{search=e.target.value;render();});$('#category-filter').addEventListener('change',e=>{category=e.target.value;render();});$('#sort').addEventListener('change',e=>{sort=e.target.value;render();});
$('#reset-filters').addEventListener('click',clearFilters);$('#demo-button').addEventListener('click',()=>{demo=!demo;view='all';clearFilters();});
$('#settings-button').addEventListener('click',()=>{$('#profile-title').value=journal.profile.title;$('#profile-subtitle').value=journal.profile.subtitle;errorIn('#profile-error','');show('#settings');});
$('#profile-form').addEventListener('submit',async event=>{event.preventDefault();try{await updateLocal(j=>({...j,profile:cleanProfile({title:$('#profile-title').value,subtitle:$('#profile-subtitle').value})}));$('#settings').close();toast('기록장 설정을 저장했어요.');}catch(e){errorIn('#profile-error',e.message);}});
$('#publish-button').addEventListener('click',openPublish);
for(const id of ['#preview-button','#publish-preview'])$(id).addEventListener('click',()=>window.open('?preview=1','_blank','noopener'));
$('#connect-form').addEventListener('submit',connect);$('#upload-button').addEventListener('click',publish);
for(const id of ['#repository','#github-token'])$(id).addEventListener('input',()=>{connection=null;$('#upload-button').hidden=true;$('#remote-summary').textContent='';});
$('#public-export').addEventListener('click',()=>{downloadJSON(snapshot,'public.json');toast('공개용 파일을 내려받았어요. GitHub에 올려야 공유돼요.');});
$('#share-button').addEventListener('click',()=>shareTrip(tripFilter));
$('#backup-button').addEventListener('click',()=>{errorIn('#backup-error','');show('#backup');});
$('#export-button').addEventListener('click',()=>{downloadJSON({...journal,exportedAt:new Date().toISOString()},'hanip-backup-'+today()+'.json');toast('사진과 메모가 담긴 백업 파일을 내려받았어요.');});
$('#import-input').addEventListener('change',async event=>{imported=null;$('#import-button').hidden=true;errorIn('#backup-error','');const file=event.target.files?.[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error('40MB 이하의 백업 파일을 선택해 주세요.');imported=parseJournal(JSON.parse(await file.text()));$('#import-summary').textContent=imported.records.length+'개의 기록을 찾았어요. 복원하면 현재 기록과 합쳐집니다.';$('#import-button').hidden=false;}catch(e){errorIn('#backup-error',e instanceof SyntaxError?'JSON 파일을 읽을 수 없어요. 올바른 백업 파일을 선택해 주세요.':e.message);}finally{event.target.value='';}});
$('#import-button').addEventListener('click',async()=>{if(!imported)return;$('#import-button').disabled=true;try{await updateLocal(j=>({...j,profile:j.records.length?j.profile:imported.profile,records:mergeRecords(j.records,imported.records)}));$('#backup').close();toast('백업 기록을 복원했어요.');imported=null;$('#import-button').hidden=true;}catch(e){errorIn('#backup-error',e.message);}finally{$('#import-button').disabled=false;}});
$('#cancel-delete').addEventListener('click',()=>$('#confirm').close());
$('#confirm-delete').addEventListener('click',async()=>{$('#confirm-delete').disabled=true;const r=journal.records.find(r=>r.id===selectedId);try{await updateLocal(j=>({...j,records:j.records.filter(x=>x.id!==selectedId)}));undoRecord=r;$('#confirm').close();$('#detail').close();toast('기록을 삭제했어요.',true);}catch(e){toast(e.message);}finally{$('#confirm-delete').disabled=false;}});
$('#undo-button').addEventListener('click',async()=>{if(!undoRecord)return;try{const r=undoRecord;await updateLocal(j=>({...j,records:[...j.records.filter(x=>x.id!==r.id),r]}));undoRecord=null;toast('기록을 다시 보관했어요.');}catch(e){toast(e.message);}});
window.addEventListener('beforeunload',event=>{if(dirty&&$('#editor').open){event.preventDefault();event.returnValue='';}});
if(channel)channel.onmessage=async()=>{if(owner){try{journal=parseJournal(await readLocal());render();}catch{toast('다른 탭의 변경을 불러오지 못했어요. 새로고침해 주세요.');}}};
async function initialize(){
 $('#records').setAttribute('aria-busy','true');
 try{if(owner||preview){journal=parseJournal(await readLocal());localReady=true;if(preview)journal=publicJournal(journal);}else{const response=await fetch('./public.json',{cache:'no-store'});if(!response.ok)throw Error('공개 기록을 불러오지 못했어요. 잠시 뒤 새로고침해 주세요.');journal=parseJournal(await response.json());journal.records=journal.records.filter(r=>r.published);}}
 catch(e){loadFailed=true;setNotice(e.message||'기록을 불러오지 못했어요. 새로고침해 주세요.',true);}
 if(!owner){$$('[data-action="new"]').forEach(b=>b.hidden=true);$('#empty h2').innerHTML='첫 여행의 기록을<br>준비하고 있어요.';$('#empty .empty-copy>p').textContent='직접 다녀온 맛집과 여행지를 이곳에서 만나보세요.';$('#empty .empty-note').textContent=preview?'‘공개할 기록에 포함하기’를 선택하면 이곳에 표시돼요.':'새로운 여행의 이야기가 곧 채워질 거예요.';}
 try{$('#repository').value=localStorage.getItem('hanip-site-repository')||guessRepository();}catch{$('#repository').value=guessRepository();}
 renderStars();render();$('#records').setAttribute('aria-busy','false');
 if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'search_travel_records',description:'Search records visible in this journal and update the visible results. Returns names only.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(!input||typeof input.query!=='string'||input.query.length>200)throw Error('query must be a string of at most 200 characters');search=input.query;$('#search').value=search;render();return {count:filtered().length,names:filtered().map(r=>r.name)};}});}catch{}}
}
initialize();
